# Generated by Django 3.0.6 on 2020-06-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='contry',
            new_name='country',
        ),
    ]
